# Copyright 2023 Decent Platforms
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

on:
  pull_request:
    branches:
      - main
      - v1.3.0
  push:
    branches:
      - main
      - v1.3.0

name: Continuous Integration

jobs:
  build:
    runs-on: ubuntu-latest
    environment: env_CI
    strategy:
      fail-fast: false
      matrix:
        go: [1.20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go}}
      - name: Fetch requirements
        run: go get ./...
      - name: Run tests
        run: go test -coverprofile=cover.out ./pkg/...
      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        with:
          path-to-profile: cover.out
          flag-name: Go-${{ matrix.go }}
          parallel: true
  finish:
    needs: build
    runs-on: ubuntu-latest
    environment: env_CI
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
